SELECT COUNT(*) AS COUNT, a.GROUPCLASSES_ID
FROM ASSETCLASSES a
GROUP BY
    a.GROUPCLASSES_ID
HAVING
    COUNT(a.GROUPCLASSES_ID) > 1;

SELECT COUNT(*) AS COUNT, g.ID
FROM GROUPCLASSES g
GROUP BY
    g.ID
HAVING
    COUNT(g.ID) > 1;

SELECT COUNT(*) AS COUNT, b.KODE_SAP
FROM BRANCHES b
GROUP BY
    b.KODE_SAP
HAVING
    COUNT(b.KODE_SAP) > 1;

SELECT COUNT(*) AS COUNT, a.NO_ASET
FROM ASSETS a
GROUP BY
    a.NO_ASET
HAVING
    COUNT(a.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, r.ENTITY
FROM "REFERENCES" r
GROUP BY
    r.ENTITY
HAVING
    COUNT(r.ENTITY) > 1;

SELECT COUNT(*) AS COUNT, d.NO_ASET
FROM DETAILASSETS d
GROUP BY
    d.NO_ASET
HAVING
    COUNT(d.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, r.ID
FROM ROLES r
GROUP BY
    r.ID
HAVING
    COUNT(r.ID) > 1;

SELECT COUNT(*) AS COUNT, c.KODE_PUSAT_BIAYA
FROM COSTCENTERS c
GROUP BY
    c.KODE_PUSAT_BIAYA
HAVING
    COUNT(c.KODE_PUSAT_BIAYA) > 1;

SELECT COUNT(*) AS COUNT, dv.NO_ASET
FROM DEPRECIATION_VALUES dv
GROUP BY
    dv.NO_ASET
HAVING
    COUNT(dv.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, e.NO_ASET
FROM ELIMINATION e
GROUP BY
    e.NO_ASET
HAVING
    COUNT(e.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, i.NO_ASET
FROM INSURANCES i
GROUP BY
    i.NO_ASET
HAVING
    COUNT(i.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, p.NO_ASET
FROM PBB p
GROUP BY
    p.NO_ASET
HAVING
    COUNT(p.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, p.NO_ASET
FROM PICTUREASSETS p
GROUP BY
    p.NO_ASET
HAVING
    COUNT(p.NO_ASET) > 1;

SELECT COUNT(*) AS COUNT, u.NO_ASET
FROM USES u
GROUP BY
    u.NO_ASET
HAVING
    COUNT(u.NO_ASET) > 1;

-- null
SELECT * FROM ASSETACCOUNTS WHERE COA IS NULL;

SELECT * FROM DETAILASSETS WHERE NO_ASET IS NULL;

SELECT * FROM BRANCHES WHERE KODE_SAP IS NULL;