-- ====================================================================
-- CHECK DUPLICATE DATA UNTUK SETIAP TABEL
-- Mengecek duplicate berdasarkan semua field business (exclude ID & dates)
-- Jalankan query satu per satu di DBeaver
-- ====================================================================

-- ASSETS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    BRANCHE_ID, NO_ASET, SUB_ASET, NAMA_ASET, KELAS_ASET, 
    KODE_CABANG, PUSAT_BIAYA, DIMENSI_NILAI, DIMENSI_SATUAN, 
    STATUS, PERIODE, TAHUN, GROUPCLASSES_ID, GROUPASSET_ID, 
    SISA_MANFAAT, PROFIT_CENTER
FROM ASSETS
GROUP BY 
    BRANCHE_ID, NO_ASET, SUB_ASET, NAMA_ASET, KELAS_ASET, 
    KODE_CABANG, PUSAT_BIAYA, DIMENSI_NILAI, DIMENSI_SATUAN, 
    STATUS, PERIODE, TAHUN, GROUPCLASSES_ID, GROUPASSET_ID, 
    SISA_MANFAAT, PROFIT_CENTER
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- DETAILASSETS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, DETAIL_MEREK, DETAIL_NO_RANGKA, 
    DETAIL_NO_MESIN, DETAIL_NO_PLAT, DETAIL_TIPE, KETERANGAN, 
    LOKASI, KORDINAT, KONDISI_FISIK, STATUS_PEROLEHAN, 
    BUKTI_KEPEMILIKAN, BUKTI_RINCIAN, BUKTI_NO, BUKTI_KETERANGAN, 
    BUKTI_FISIK_DOKUMEN, STATUS_ITEMINISASI, PERIODE, TAHUN, 
    STATUS_PENGELOLAAN
FROM DETAILASSETS
WHERE NO_ASET IS NOT NULL
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, DETAIL_MEREK, DETAIL_NO_RANGKA, 
    DETAIL_NO_MESIN, DETAIL_NO_PLAT, DETAIL_TIPE, KETERANGAN, 
    LOKASI, KORDINAT, KONDISI_FISIK, STATUS_PEROLEHAN, 
    BUKTI_KEPEMILIKAN, BUKTI_RINCIAN, BUKTI_NO, BUKTI_KETERANGAN, 
    BUKTI_FISIK_DOKUMEN, STATUS_ITEMINISASI, PERIODE, TAHUN, 
    STATUS_PENGELOLAAN
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- DEPRECIATION_VALUES  
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NILAI_SUSUT, AKUMULASI_PENYUSUTAN, 
    NILAI_PEROLEHAN, NILAI_BUKU, NILAI_RESIDU, PERIODE, TAHUN
FROM DEPRECIATION_VALUES
GROUP BY 
    NO_ASET, SUB_ASET, NILAI_SUSUT, AKUMULASI_PENYUSUTAN, 
    NILAI_PEROLEHAN, NILAI_BUKU, NILAI_RESIDU, PERIODE, TAHUN
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- ELIMINATION
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, PENGHAPUSAN_RINCIAN, 
    PENGHAPUSAN_NOMOR, PENGHAPUSAN_KETERANGAN, STATUS, 
    PERIODE, TAHUN
FROM ELIMINATION
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, PENGHAPUSAN_RINCIAN, 
    PENGHAPUSAN_NOMOR, PENGHAPUSAN_KETERANGAN, STATUS, 
    PERIODE, TAHUN
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- INSURANCES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, RINCIAN, NO_POLIS, 
    PREMI, KETERANGAN_ASURANSI, ALASAN_ASURANSI, STATUS, 
    PERIODE, TAHUN, NO_ASURANSI
FROM INSURANCES
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, RINCIAN, NO_POLIS, 
    PREMI, KETERANGAN_ASURANSI, ALASAN_ASURANSI, STATUS, 
    PERIODE, TAHUN, NO_ASURANSI
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- PBB
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, NJOP, NO_PBB, 
    PERIODE, TAHUN, KETERANGAN_PBB
FROM PBB
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, NJOP, NO_PBB, 
    PERIODE, TAHUN, KETERANGAN_PBB
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- PICTUREASSETS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, PATH_SURAT, FLAG, JENIS_FOTO
FROM PICTUREASSETS
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, PATH_SURAT, FLAG, JENIS_FOTO
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- USES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NO_ASET, SUB_ASET, NO_ITEM, STATUS_PENGELOLAAN_RINCIAN, 
    NAMA_PENYEWA, NO_KONTRAK_SEWA, PIHAK_YANG_MENEMPATI, 
    TAHUN, PERIODE, USES_TYPE, NO_USES
FROM USES
GROUP BY 
    NO_ASET, SUB_ASET, NO_ITEM, STATUS_PENGELOLAAN_RINCIAN, 
    NAMA_PENYEWA, NO_KONTRAK_SEWA, PIHAK_YANG_MENEMPATI, 
    TAHUN, PERIODE, USES_TYPE, NO_USES
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- BRANCHES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NAMA_CABANG, KODE_REGIONAL, KODE_TERMINAL, KODE_SAP, 
    PROFIT_CENTER, FLAG_APPROVE
FROM BRANCHES
GROUP BY 
    NAMA_CABANG, KODE_REGIONAL, KODE_TERMINAL, KODE_SAP, 
    PROFIT_CENTER, FLAG_APPROVE
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- COSTCENTERS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    KODE_PUSAT_BIAYA, NAMA_PUSAT_BIAYA, FLAG
FROM COSTCENTERS
GROUP BY 
    KODE_PUSAT_BIAYA, NAMA_PUSAT_BIAYA, FLAG
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- ASSETCLASSES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    ASET_KELAS, DESKRIPSI, KET, GROUPASSET_ID, 
    GROUPCLASSES_ID, FLAG
FROM ASSETCLASSES
GROUP BY 
    ASET_KELAS, DESKRIPSI, KET, GROUPASSET_ID, 
    GROUPCLASSES_ID, FLAG
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- GROUPCLASSES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NAMA_GROUP_KELAS, KODE
FROM GROUPCLASSES
GROUP BY 
    NAMA_GROUP_KELAS, KODE
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- GROUPASSETS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NAMA_GROUP
FROM GROUPASSETS
GROUP BY 
    NAMA_GROUP
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- REFERENCES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    KATEGORI, ENTITY, NAMA_ENTITY, FLAG
FROM "REFERENCES"
GROUP BY 
    KATEGORI, ENTITY, NAMA_ENTITY, FLAG
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- ROLES
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NAME, ID_MENU, STATUS, ID_INTEGRATION
FROM ROLES
GROUP BY 
    NAME, ID_MENU, STATUS, ID_INTEGRATION
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- USERS
SELECT 
    COUNT(*) AS DUPLICATE_COUNT,
    NAME, EMAIL, ID_CABANG, ID_ROLE, STATUS, KODE_REGIONAL
FROM USERS
GROUP BY 
    NAME, EMAIL, ID_CABANG, ID_ROLE, STATUS, KODE_REGIONAL
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;