-- add new columns to the tables
ALTER TABLE "ASSETCLASSES"
ADD (
    "GROUPASSET_ID" NUMBER,
    "GROUPCLASSES_ID" NUMBER
);

ALTER TABLE "ASSETS"
ADD (
    "KELAS_ASET" NUMBER,
    "GROUPASSET_ID" NUMBER
);

ALTER TABLE "BRANCHES" ADD ("ID_CABANG" NUMBER);

ALTER TABLE "GROUPASSETS" ADD ("ID" NUMBER);

ALTER TABLE "ROLES" ADD ("ID" NUMBER);

ALTER TABLE "USERS"
ADD (
    "ID_CABANG" NUMBER,
    "ID_ROLE" NUMBER
);

ALTER TABLE "USES" ADD ("NO_ITEM" NUMBER (2, 0));

-- fill new columns with the values from the old columns
UPDATE "ASSETCLASSES"
SET
    GROUPASSET_ID = TO_NUMBER(
        REGEXP_REPLACE(GROUPASSET_ID2, '[^0-9]', '')
    ),
    GROUPCLASSES_ID = TO_NUMBER(
        REGEXP_REPLACE(
            GROUPCLASSES_ID2,
            '[^0-9]',
            ''
        )
    );

UPDATE "ASSETS"
SET
    KELAS_ASET = TO_NUMBER(
        REGEXP_REPLACE(KELAS_ASET2, '[^0-9]', '')
    ),
    GROUPASSET_ID = TO_NUMBER(
        REGEXP_REPLACE(GROUPASSET_ID2, '[^0-9]', '')
    );

UPDATE "BRANCHES"
SET
    ID_CABANG = TO_NUMBER(
        REGEXP_REPLACE(ID_CABANG2, '[^0-9]', '')
    );

UPDATE "GROUPASSETS"
SET
    ID = TO_NUMBER(
        REGEXP_REPLACE(ID2, '[^0-9]', '')
    );

UPDATE "ROLES"
SET
    ID = TO_NUMBER(
        REGEXP_REPLACE(ID2, '[^0-9]', '')
    );

UPDATE "USERS"
SET
    ID_CABANG = TO_NUMBER(
        REGEXP_REPLACE(ID_CABANG2, '[^0-9]', '')
    ),
    ID_ROLE = TO_NUMBER(
        REGEXP_REPLACE(ID_ROLE2, '[^0-9]', '')
    );

UPDATE "USES"
SET
    NO_ITEM = TO_NUMBER(
        REGEXP_REPLACE(NO_ITEM2, '[^0-9]', '')
    );

-- drop old columns
ALTER TABLE "ASSETCLASSES"
DROP (
    "GROUPASSET_ID2",
    "GROUPCLASSES_ID2"
);

ALTER TABLE "ASSETS" DROP ( "KELAS_ASET2", "GROUPASSET_ID2" );

ALTER TABLE "BRANCHES" DROP ("ID_CABANG2");

ALTER TABLE "GROUPASSETS" DROP ("ID2");

ALTER TABLE "ROLES" DROP ("ID2");

ALTER TABLE "USERS" DROP ("ID_CABANG2", "ID_ROLE2");

ALTER TABLE "USES" DROP ("NO_ITEM2");