-- Table structure for all tables in the database
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."ASSETCLASSES" MODIFY (
    "GROUPASSET_ID" NUMBER,
    "GROUPCLASSES_ID" NUMBER
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."ASSETS" MODIFY (
    "KELAS_ASET" NUMBER,
    "GROUPASSET_ID" NUMBER
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."BRANCHES" MODIFY (
    "ID_CABANG" NUMBER,
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."GROUPASSETS" MODIFY (
    "ID" NUMBER
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."ROLES" MODIFY (
    "ID" NUMBER
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."USERS" MODIFY (
    "ID_CABANG" NUMBER,
    "ID_ROLE" NUMBER
  )';

  EXECUTE IMMEDIATE 'ALTER TABLE "C##SIAPDEV3"."USES" MODIFY (
    "NO_ITEM" NUMBER (2, 0)
  )';
END;