ALTER TABLE "ASSETCLASSES" MODIFY (
    "GROUPASSET_ID" NUMBER,
    "GROUPCLASSES_ID" NUMBER
);

ALTER TABLE "ASSETS" MODIFY (
    "KELAS_ASET" NUMBER,
    "GROUPASSET_ID" NUMBER
);

ALTER TABLE "BRANCHES" MODIFY ("ID_CABANG" NUMBER,);

ALTER TABLE "GROUPASSETS" MODIFY ("ID" NUMBER);

ALTER TABLE "ROLES" MODIFY ("ID" NUMBER);

ALTER TABLE "USERS" MODIFY (
    "ID_CABANG" NUMBER,
    "ID_ROLE" NUMBER
);

ALTER TABLE "USES" MODIFY ("NO_ITEM" NUMBER (2, 0));