-- add new columns to the tables
ALTER TABLE "ASSETCLASSES"
ADD (
    "GROUPASSET_ID2" NUMBER,
    "GROUPCLASSES_ID2" NUMBER
);

ALTER TABLE "ASSETS"
ADD (
    "KELAS_ASET2" NUMBER,
    "GROUPASSET_ID2" NUMBER
);

ALTER TABLE "BRANCHES" ADD ("ID_CABANG2" NUMBER);

ALTER TABLE "GROUPASSETS" ADD ("ID2" NUMBER);

ALTER TABLE "ROLES" ADD ("ID2" NUMBER);

ALTER TABLE "USERS"
ADD (
    "ID_CABANG2" NUMBER,
    "ID_ROLE2" NUMBER
);

ALTER TABLE "USES" ADD ("NO_ITEM2" NUMBER (2, 0));

-- fill new columns with the values from the old columns
UPDATE "ASSETCLASSES"
SET
    GROUPASSET_ID2 = TO_NUMBER(
        REGEXP_REPLACE(GROUPASSET_ID, '[^0-9]', '')
    ),
    GROUPCLASSES_ID2 = TO_NUMBER(
        REGEXP_REPLACE(GROUPCLASSES_ID, '[^0-9]', '')
    );

UPDATE "ASSETS"
SET
    KELAS_ASET2 = TO_NUMBER(
        REGEXP_REPLACE(KELAS_ASET, '[^0-9]', '')
    ),
    GROUPASSET_ID2 = TO_NUMBER(
        REGEXP_REPLACE(GROUPASSET_ID, '[^0-9]', '')
    );

UPDATE "BRANCHES"
SET
    ID_CABANG2 = TO_NUMBER(
        REGEXP_REPLACE(ID_CABANG, '[^0-9]', '')
    );

UPDATE "GROUPASSETS"
SET
    ID2 = TO_NUMBER(
        REGEXP_REPLACE(ID, '[^0-9]', '')
    );

UPDATE "ROLES"
SET
    ID2 = TO_NUMBER(
        REGEXP_REPLACE(ID, '[^0-9]', '')
    );

UPDATE "USERS"
SET
    ID_CABANG2 = TO_NUMBER(
        REGEXP_REPLACE(ID_CABANG, '[^0-9]', '')
    ),
    ID_ROLE2 = TO_NUMBER(
        REGEXP_REPLACE(ID_ROLE, '[^0-9]', '')
    );

UPDATE "USES"
SET
    NO_ITEM2 = TO_NUMBER(
        REGEXP_REPLACE(NO_ITEM, '[^0-9]', '')
    );

-- drop old columns
ALTER TABLE "ASSETCLASSES"
DROP (
    "GROUPASSET_ID",
    "GROUPCLASSES_ID"
);

ALTER TABLE "ASSETS" DROP ("KELAS_ASET", "GROUPASSET_ID");

ALTER TABLE "BRANCHES" DROP ("ID_CABANG");

ALTER TABLE "GROUPASSETS" DROP ("ID");

ALTER TABLE "ROLES" DROP ("ID");

ALTER TABLE "USERS" DROP ("ID_CABANG", "ID_ROLE");

ALTER TABLE "USES" DROP ("NO_ITEM");