DELETE FROM ASSETCLASSES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM ASSETCLASSES
        GROUP BY
            GROUPCLASSES_ID
    );

DELETE FROM GROUPCLASSES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM GROUPCLASSES
        GROUP BY
            ID
    );

DELETE FROM BRANCHES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM BRANCHES
        GROUP BY
            KODE_SAP
        HAVING
            COUNT(*) > 1
    );

DELETE FROM ASSETS
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM ASSETS
        GROUP BY
            NO_ASET
        HAVING
            COUNT(*) > 1
    );

DELETE FROM "REFERENCES"
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM "REFERENCES"
        GROUP BY
            ENTITY
        HAVING
            COUNT(*) > 1
    );

DELETE FROM DETAILASSETS
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM DETAILASSETS
        GROUP BY
            NO_ASET
        HAVING
            COUNT(*) > 1
    );

DELETE FROM ROLES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM ROLES
        GROUP BY
            ID
        HAVING
            COUNT(*) > 1
    );

DELETE FROM COSTCENTERS
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM COSTCENTERS
        GROUP BY
            KODE_PUSAT_BIAYA
    );

DELETE FROM DEPRECIATION_VALUES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM DEPRECIATION_VALUES
        GROUP BY
            NO_ASET
    );

DELETE FROM ELIMINATION
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM ELIMINATION
        GROUP BY
            NO_ASET
    );

DELETE FROM INSURANCES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM INSURANCES
        GROUP BY
            NO_ASET
    );

DELETE FROM PBB
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM PBB
        GROUP BY
            NO_ASET
    );

DELETE FROM PICTUREASSETS
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM PICTUREASSETS
        GROUP BY
            NO_ASET
    );

DELETE FROM USES
WHERE
    ROWID NOT IN (
        SELECT MIN(ROWID)
        FROM USES
        GROUP BY
            NO_ASET
    );

-- null
DELETE FROM ASSETACCOUNTS WHERE COA IS NULL;

DELETE FROM DETAILASSETS WHERE NO_ASET IS NULL;

DELETE FROM BRANCHES WHERE KODE_SAP IS NULL;