DELETE FROM ASSETCLASSES
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM ASSETCLASSES
  GROUP BY GROUPCLASSES_ID
);

DELETE FROM GROUPCLASSES
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM GROUPCLASSES
  GROUP BY ID
);

DELETE FROM BRANCHES
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM BRANCHES
  GROUP BY KODE_SAP
  HAVING COUNT(*) > 1
);

DELETE FROM ASSETS
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM ASSETS
  GROUP BY NO_ASET
  HAVING COUNT(*) > 1
);

DELETE FROM "REFERENCES"
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM "REFERENCES"
  GROUP BY ENTITY
  HAVING COUNT(*) > 1
);

DELETE FROM DETAILASSETS
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM DETAILASSETS
  GROUP BY NO_ASET
  HAVING COUNT(*) > 1
);

DELETE FROM ROLES
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM ROLES
  GROUP BY ID
  HAVING COUNT(*) > 1
);
