UPDATE 
    "ASSETCLASSES"
SET 
    GROUPASSET_ID = REGEXP_REPLACE(GROUPASSET_ID, '[^0-9]', ''),
    GROUPCLASSES_ID = REGEXP_REPLACE(GROUPCLASSES_ID, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(GROUPASSET_ID, '[^0-9]')
    OR
    REGEXP_LIKE(GROUPCLASSES_ID, '[^0-9]');

UPDATE 
    "ASSETS"
SET 
    KELAS_ASET = REGEXP_REPLACE(KELAS_ASET, '[^0-9]', ''),
    GROUPASSET_ID = REGEXP_REPLACE(GROUPASSET_ID, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(KELAS_ASET, '[^0-9]')
    OR
    REGEXP_LIKE(GROUPASSET_ID, '[^0-9]');

UPDATE 
    "BRANCHES"
SET 
    ID_CABANG = REGEXP_REPLACE(ID_CABANG, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(ID_CABANG, '[^0-9]');

UPDATE 
    "GROUPASSETS"
SET 
    ID = REGEXP_REPLACE(ID, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(ID, '[^0-9]');

UPDATE 
    "ROLES"
SET 
    ID = REGEXP_REPLACE(ID, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(ID, '[^0-9]');

UPDATE 
    "USERS"
SET 
    ID_CABANG = REGEXP_REPLACE(ID_CABANG, '[^0-9]', ''),
    ID_ROLE = REGEXP_REPLACE(ID_ROLE, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(ID_CABANG, '[^0-9]')
    OR
    REGEXP_LIKE(ID_ROLE, '[^0-9]');

UPDATE 
    "USES"
SET 
    NO_ITEM = REGEXP_REPLACE(NO_ITEM, '[^0-9]', '')
WHERE 
    REGEXP_LIKE(NO_ITEM, '[^0-9]');