SELECT COUNT(GROUPCLASSES_ID)
FROM ASSETS
WHERE GROUPCLASSES_ID NOT IN (
	SELECT GROUPCLASSES_ID
	FROM ASSETCLASSES
);

SELECT COUNT(KELAS_ASET)
FROM ASSETS
WHERE KELAS_ASET NOT IN (
	SELECT ID
	FROM GROUPCLASSES
);

SELECT COUNT(KODE_CABANG)
FROM ASSETS
WHERE KODE_CABANG NOT IN (
	SELECT KODE_SAP
	FROM BRANCHES
);

SELECT COUNT(NO_ASET)
FROM DEPRECIATION_VALUES
WHERE NO_ASET NOT IN (
	SELECT NO_ASET
	FROM ASSETS
);

SELECT COUNT(KONDISI_FISIK)
FROM DETAILASSETS
WHERE KONDISI_FISIK NOT IN (
	SELECT ENTITY
	FROM "REFERENCES"
);

SELECT COUNT(STATUS_PEROLEHAN)
FROM DETAILASSETS
WHERE STATUS_PEROLEHAN NOT IN (
	SELECT ENTITY
	FROM "REFERENCES"
);

SELECT COUNT(NO_ASET)
FROM DETAILASSETS
WHERE NO_ASET NOT IN (
	SELECT NO_ASET
	FROM ASSETS
);

SELECT COUNT(NO_ASET)
FROM PICTUREASSETS
WHERE NO_ASET NOT IN (
	SELECT NO_ASET
	FROM DETAILASSETS
);

SELECT COUNT(ID_ROLE)
FROM USERS
WHERE ID_ROLE NOT IN (
	SELECT ID
	FROM ROLES
);

SELECT COUNT(NO_ASET)
FROM USES
WHERE NO_ASET NOT IN (
	SELECT NO_ASET
	FROM ASSETS
);
