SELECT
  COUNT(*) AS COUNT,
  a.GROUPCLASSES_ID
FROM ASSETCLASSES a 
GROUP BY a.GROUPCLASSES_ID
  HAVING COUNT(a.GROUPCLASSES_ID) > 1;

SELECT 
	COUNT(*) AS COUNT,
	g.ID 
FROM GROUPCLASSES g 
GROUP BY g.ID
	HAVING COUNT(g.ID) > 1;

SELECT
	COUNT(*) AS COUNT,
	b.KODE_SAP
FROM BRANCHES b
GROUP BY b.KODE_SAP
	HAVING COUNT(b.KODE_SAP) > 1;

SELECT 
	COUNT(*) AS COUNT,
	a.NO_ASET
FROM ASSETS a
GROUP BY a.NO_ASET
	HAVING COUNT(a.NO_ASET) > 1;

SELECT 
	COUNT(*) AS COUNT,
	r.ENTITY
FROM "REFERENCES" r 
GROUP BY r.ENTITY
	HAVING COUNT(r.ENTITY) > 1;

SELECT
	COUNT(*) AS COUNT,
	d.NO_ASET
FROM DETAILASSETS d
GROUP BY d.NO_ASET
	HAVING COUNT(d.NO_ASET) > 1;

SELECT
	COUNT(*) AS COUNT,
	r.ID
FROM ROLES r 
GROUP BY r.ID
	HAVING COUNT(r.ID) > 1;