BEGIN
  -- Update BRANCHE_ID AT ASSETS TABLE
  EXECUTE IMMEDIATE '
    UPDATE ASSETS A
    SET A.BRANCHE_ID = (
        SELECT MAX(B.ID_CABANG)
        FROM BRANCHES B
        WHERE B.KODE_SAP = A.KODE_CABANG
          AND B.PROFIT_CENTER = A.PROFIT_CENTER
    )
    WHERE EXISTS (
        SELECT 1
        FROM BRANCHES B
        WHERE B.KODE_SAP = A.KODE_CABANG
          AND B.PROFIT_CENTER = A.PROFIT_CENTER
    )';
  
  DBMS_OUTPUT.PUT_LINE('✅ Updated BRANCH_ID in ASSETS');

  -- update ASSETCLASSES_ID AT ASSETS TABLE
  EXECUTE IMMEDIATE '
    UPDATE ASSETS A
    SET A.ASSETCLASSES_ID = (
        SELECT MAX(AC.ID)
        FROM ASSETCLASSES AC
        WHERE SUBSTR(A.KELAS_ASET, 1, 6) = SUBSTR(AC.ASET_KELAS, 1, 6)
          AND SUBSTR(A.GROUPASSET_ID, 1, 4) = SUBSTR(AC.GROUPASSET_ID, 1, 4)
          AND SUBSTR(A.GROUPCLASSES_ID, 1, 6) = SUBSTR(AC.GROUPCLASSES_ID, 1, 6)
    )
    WHERE EXISTS (
        SELECT 1
        FROM ASSETCLASSES AC
        WHERE SUBSTR(A.KELAS_ASET, 1, 6) = SUBSTR(AC.ASET_KELAS, 1, 6)
          AND SUBSTR(A.GROUPASSET_ID, 1, 4) = SUBSTR(AC.GROUPASSET_ID, 1, 4)
          AND SUBSTR(A.GROUPCLASSES_ID, 1, 6) = SUBSTR(AC.GROUPCLASSES_ID, 1, 6)
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated ASSETCLASSES_ID in ASSETS');

  -- Update ASSETS_ID at DETAILASSETS table with latest data
  EXECUTE IMMEDIATE '
    UPDATE DETAILASSETS DA
    SET DA.ASSET_ID = (
      SELECT MAX(A.ID)
      FROM ASSETS A
      WHERE DA.NO_ASET = A.NO_ASET
        AND DA.SUB_ASET = A.SUB_ASET
        AND DA.PERIODE = A.PERIODE
        AND DA.TAHUN = A.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM ASSETS A
      WHERE DA.NO_ASET = A.NO_ASET
        AND DA.SUB_ASET = A.SUB_ASET
        AND DA.PERIODE = A.PERIODE
        AND DA.TAHUN = A.TAHUN
    )';
  
  DBMS_OUTPUT.PUT_LINE('✅ Updated ASSET_ID in DETAILASSETS');

  EXECUTE IMMEDIATE '
    UPDATE DETAILASSETS DA
    SET DA.PBB_ID = (
      SELECT MAX(P.ID)
      FROM PBB P
      WHERE P.NO_ASET = DA.NO_ASET
        AND P.SUB_ASET = DA.SUB_ASET
        AND P.PERIODE = DA.PERIODE
        AND P.TAHUN = DA.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM PBB P
      WHERE P.NO_ASET = DA.NO_ASET
        AND P.SUB_ASET = DA.SUB_ASET
        AND P.PERIODE = DA.PERIODE
        AND P.TAHUN = DA.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated PBB_ID in DETAILASSETS');

  EXECUTE IMMEDIATE '
    UPDATE DETAILASSETS DA
    SET DA.INSURANCE_ID = (
      SELECT MAX(I.ID)
      FROM INSURANCES I
      WHERE I.NO_ASET = DA.NO_ASET
        AND I.SUB_ASET = DA.SUB_ASET
        AND I.PERIODE = DA.PERIODE
        AND I.TAHUN = DA.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM INSURANCES I
      WHERE I.NO_ASET = DA.NO_ASET
        AND I.SUB_ASET = DA.SUB_ASET
        AND I.PERIODE = DA.PERIODE
        AND I.TAHUN = DA.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated INSURANCE_ID in DETAILASSETS');

  EXECUTE IMMEDIATE '
    UPDATE DETAILASSETS DA
    SET DA.DEPRECIATION_VALUE_ID = (
      SELECT MAX(DV.ID)
      FROM DEPRECIATION_VALUES DV
      WHERE DV.NO_ASET = DA.NO_ASET
        AND DV.SUB_ASET = DA.SUB_ASET
        AND DV.PERIODE = DA.PERIODE
        AND DV.TAHUN = DA.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM DEPRECIATION_VALUES DV
      WHERE DV.NO_ASET = DA.NO_ASET
        AND DV.SUB_ASET = DA.SUB_ASET
        AND DV.PERIODE = DA.PERIODE
        AND DV.TAHUN = DA.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated DEPRECIATION_VALUE_ID in DETAILASSETS');

  EXECUTE IMMEDIATE '
    UPDATE DETAILASSETS DA
    SET DA.ELIMINATION_ID = (
      SELECT MAX(E.ID)
      FROM ELIMINATION E
      WHERE E.NO_ASET = DA.NO_ASET
        AND E.SUB_ASET = DA.SUB_ASET
        AND E.PERIODE = DA.PERIODE
        AND E.TAHUN = DA.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM ELIMINATION E
      WHERE E.NO_ASET = DA.NO_ASET
        AND E.SUB_ASET = DA.SUB_ASET
        AND E.PERIODE = DA.PERIODE
        AND E.TAHUN = DA.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated ELIMINATION_ID in DETAILASSETS');

  EXECUTE IMMEDIATE '
      UPDATE PICTUREASSETS PA
      SET PA.DETAILASSET_ID = (
        SELECT MAX(DA.ID)
        FROM DETAILASSETS DA
        WHERE DA.NO_ASET = PA.NO_ASET
          AND DA.SUB_ASET = PA.SUB_ASET
      )
      WHERE EXISTS (
        SELECT 1
        FROM DETAILASSETS DA
        WHERE DA.NO_ASET = PA.NO_ASET
          AND DA.SUB_ASET = PA.SUB_ASET
      )
    ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated DETAILASSET_ID in PICTUREASSETS');

  EXECUTE IMMEDIATE '
    UPDATE USES U
    SET U.DETAILASSET_ID = (
      SELECT MAX(DA.ID)
      FROM DETAILASSETS DA
      WHERE DA.NO_ASET = U.NO_ASET
        AND DA.SUB_ASET = U.SUB_ASET
        AND DA.PERIODE = U.PERIODE
        AND DA.TAHUN = U.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM DETAILASSETS DA
      WHERE DA.NO_ASET = U.NO_ASET
        AND DA.SUB_ASET = U.SUB_ASET
        AND DA.PERIODE = U.PERIODE
        AND DA.TAHUN = U.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated DETAILASSET_ID in USES');

  EXECUTE IMMEDIATE '
    UPDATE NOTIFIKASI N
    SET N.DETAILASSET_ID = (
      SELECT MAX(DA.ID)
      FROM DETAILASSETS DA
      WHERE DA.NO_ASET = N.NO_ASET
        AND DA.PERIODE = N.PERIODE
        AND DA.TAHUN = N.TAHUN
    )
    WHERE EXISTS (
      SELECT 1
      FROM DETAILASSETS DA
      WHERE DA.NO_ASET = N.NO_ASET
        AND DA.PERIODE = N.PERIODE
        AND DA.TAHUN = N.TAHUN
    )
  ';

  DBMS_OUTPUT.PUT_LINE('✅ Updated DETAILASSET_ID in NOTIFIKASI');
END;