DECLARE
  v_sql VARCHAR2(4000);
BEGIN
  -- Drop existing constraints
  FOR r IN (
    SELECT constraint_name, table_name 
    FROM user_constraints 
    WHERE constraint_type IN ('R', 'U') 
    AND constraint_name IN (
      'FK_USERS_ROLES',
      'FK_ASSETS_GROUPCLASSES',
      'FK_PICTURES_DETAILASSETS',
      'FK_ASSETS_ASSETCLASSES',
      'IDX_ASSETS_NATURAL_KEY',
      'IDX_BRANCHES_SAP',
      'IDX_REFERENCES_ENTITY'
    )
  ) LOOP
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."' || r.table_name || '" DROP CONSTRAINT "' || r.constraint_name || '"';
    BEGIN
      EXECUTE IMMEDIATE v_sql;
    EXCEPTION WHEN OTHERS THEN
      NULL; -- Ignore any errors during drop
    END;
  END LOOP;

  -- Drop indexes if they exist
  FOR r IN (
    SELECT index_name 
    FROM user_indexes 
    WHERE index_name IN (
      'IDX_ASSETS_NATURAL_KEY',
      'IDX_BRANCHES_SAP',
      'IDX_REFERENCES_ENTITY'
    )
  ) LOOP
    v_sql := 'DROP INDEX "' || r.index_name || '"';
    BEGIN
      EXECUTE IMMEDIATE v_sql;
    EXCEPTION WHEN OTHERS THEN
      NULL; -- Ignore any errors during drop
    END;
  END LOOP;

  -- Create unique constraints instead of indexes to support foreign keys
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "UK_ASSETS_ASSET_ID" UNIQUE ("NO_ASET", "SUB_ASET")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2261 THEN -- Ignore if constraint already exists
      DBMS_OUTPUT.PUT_LINE('Error creating UK_ASSETS_ASSET_ID: ' || SQLERRM);
    END IF;
  END;

  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "UK_ASSETS_NATURAL_KEY" UNIQUE ("NO_ASET", "SUB_ASET", "PERIODE", "TAHUN")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2261 THEN -- Ignore if constraint already exists
      DBMS_OUTPUT.PUT_LINE('Error creating UK_ASSETS_NATURAL_KEY: ' || SQLERRM);
    END IF;
  END;

  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."BRANCHES" ADD CONSTRAINT "UK_BRANCHES_SAP" UNIQUE ("KODE_SAP")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2261 THEN -- Ignore if constraint already exists
      DBMS_OUTPUT.PUT_LINE('Error creating UK_BRANCHES_SAP: ' || SQLERRM);
    END IF;
  END;

  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."REFERENCES" ADD CONSTRAINT "UK_REFERENCES_ENTITY" UNIQUE ("ENTITY")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2261 THEN -- Ignore if constraint already exists
      DBMS_OUTPUT.PUT_LINE('Error creating UK_REFERENCES_ENTITY: ' || SQLERRM);
    END IF;
  END;

  -- Now create foreign key constraints
  -- Users & Roles Relation
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."USERS" ADD CONSTRAINT "FK_USERS_ROLES" FOREIGN KEY ("ID_ROLE") REFERENCES "C##SIAPDEV4"."ROLES"("ID")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_USERS_ROLES: ' || SQLERRM);
  END;

  -- DetailAssets & Assets Relation - now references full unique key
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."DETAILASSETS" ADD CONSTRAINT "FK_DETAILASSETS_ASSETS" FOREIGN KEY ("NO_ASET", "SUB_ASET") REFERENCES "C##SIAPDEV4"."ASSETS"("NO_ASET", "SUB_ASET") ON DELETE CASCADE';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_DETAILASSETS_ASSETS: ' || SQLERRM);
  END;

  -- Assets & GroupClasses Relation
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "FK_ASSETS_GROUPCLASSES" FOREIGN KEY ("KELAS_ASET") REFERENCES "C##SIAPDEV4"."GROUPCLASSES"("ID")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_ASSETS_GROUPCLASSES: ' || SQLERRM);
  END;

  -- Assets & Branches Relation
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "FK_ASSETS_BRANCHES" FOREIGN KEY ("KODE_CABANG") REFERENCES "C##SIAPDEV4"."BRANCHES"("KODE_SAP")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_ASSETS_BRANCHES: ' || SQLERRM);
  END;

  -- DepreciationValues & Assets Relation - now references full unique key
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."DEPRECIATION_VALUES" ADD CONSTRAINT "FK_DEPRECIATION_ASSETS" FOREIGN KEY ("NO_ASET", "SUB_ASET") REFERENCES "C##SIAPDEV4"."ASSETS"("NO_ASET", "SUB_ASET") ON DELETE CASCADE';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_DEPRECIATION_ASSETS: ' || SQLERRM);
  END;

  -- PictureAssets & DetailAssets Relation
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."PICTUREASSETS" ADD CONSTRAINT "FK_PICTURES_DETAILASSETS" FOREIGN KEY ("NO_ASET", "SUB_ASET", "NO_ITEM") REFERENCES "C##SIAPDEV4"."DETAILASSETS"("NO_ASET", "SUB_ASET", "NO_ITEM")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_PICTURES_DETAILASSETS: ' || SQLERRM);
  END;

  -- Uses & Assets Relation - now references full unique key
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."USES" ADD CONSTRAINT "FK_USES_ASSETS" FOREIGN KEY ("NO_ASET", "SUB_ASET") REFERENCES "C##SIAPDEV4"."ASSETS"("NO_ASET", "SUB_ASET") ON DELETE CASCADE';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_USES_ASSETS: ' || SQLERRM);
  END;

  -- Assets & AssetClasses Relation
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "FK_ASSETS_ASSETCLASSES" FOREIGN KEY ("GROUPCLASSES_ID") REFERENCES "C##SIAPDEV4"."ASSETCLASSES"("GROUPCLASSES_ID")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_ASSETS_ASSETCLASSES: ' || SQLERRM);
  END;

  -- DetailAssets & References Relations (for kondisi_fisik)
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."DETAILASSETS" ADD CONSTRAINT "FK_DETAILASSETS_REFERENCES_KONDISI" FOREIGN KEY ("KONDISI_FISIK") REFERENCES "C##SIAPDEV4"."REFERENCES"("ENTITY")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_DETAILASSETS_REFERENCES_KONDISI: ' || SQLERRM);
  END;

  -- DetailAssets & References Relations (for status_perolehan)
  BEGIN
    v_sql := 'ALTER TABLE "C##SIAPDEV4"."DETAILASSETS" ADD CONSTRAINT "FK_DETAILASSETS_REFERENCES_STATUS" FOREIGN KEY ("STATUS_PEROLEHAN") REFERENCES "C##SIAPDEV4"."REFERENCES"("ENTITY")';
    EXECUTE IMMEDIATE v_sql;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating FK_DETAILASSETS_REFERENCES_STATUS: ' || SQLERRM);
  END;
END;
