-- ASSETACCOUNTS
-- ASSETCLASSES
ALTER TABLE "C##SIAPDEV4"."ASSETS" ADD CONSTRAINT "ASSETS_PK" PRIMARY KEY ("NO_ASET", "SUB_ASET", "PERIODE", "TAHUN");
ALTER TABLE "C##SIAPDEV4"."ASSET_SAP_FAILED" ADD CONSTRAINT "ASSET_SAP_FAILED_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."BRANCHES" ADD CONSTRAINT "BRANCHES_PK" PRIMARY KEY ("ID_CABANG");
-- COSTCENTERS
-- DEPRECIATIONS
ALTER TABLE "C##SIAPDEV4"."DEPRECIATION_VALUES" ADD CONSTRAINT "DEPRECIATION_VALUES_PK" PRIMARY KEY ("NO_ASET", "SUB_ASET", "PERIODE", "TAHUN");
-- DETAILASSETS
-- DIMENSI_SATUAN
-- ELIMINATION
ALTER TABLE "C##SIAPDEV4"."GROUPASSETS" ADD CONSTRAINT "GROUPASSETS_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."GROUPCLASSES" ADD CONSTRAINT "GROUPCLASSES_ID_PK" PRIMARY KEY ("ID");
-- INSURANCES
ALTER TABLE "C##SIAPDEV4"."MASTER_ASURANSI" ADD CONSTRAINT "MASTER_ASURANSI_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."MONITORING_FAILED" ADD CONSTRAINT "MONITORING_FAILED_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."MONITORING_INTEGRATOR" ADD CONSTRAINT "MONITORING_INTEGRATOR_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."NOTIFIKASI" ADD CONSTRAINT "NOTIFIKASI_PK" PRIMARY KEY ("ID_NOTIFIKASI");
ALTER TABLE "C##SIAPDEV4"."PBB" ADD CONSTRAINT "PBB_PK" PRIMARY KEY ("NO_ASET", "SUB_ASET", "NO_ITEM", "TAHUN", "PERIODE");
ALTER TABLE "C##SIAPDEV4"."PERIOD" ADD CONSTRAINT "PERIOD_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."PERIOD_REQUEST" ADD CONSTRAINT "PERIOD_REQUEST_PK" PRIMARY KEY ("ID");
-- PICTUREASSETS
-- REFERENCES
ALTER TABLE "C##SIAPDEV4"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID");
ALTER TABLE "C##SIAPDEV4"."USERS" ADD CONSTRAINT "USERS_ID_PK" PRIMARY KEY ("ID");
-- USES